application: clearfix-svr1
version: deppo
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:

- url: /robots.txt
  static_files: frontend/robots.txt
  upload: frontend/robots.txt

- url: /img
  static_dir: frontend/img
- url: /img/placeholder
  static_dir: frontend/img/placeholder
- url: /stylesheets
  static_dir: frontend/stylesheets
- url: /bower_components
  static_dir: frontend/bower_components
- url: /fonts
  static_dir: frontend/fonts
- url: /js
  static_dir: frontend/js
- url: /scss
  static_dir: frontend/scss


- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup


error_handlers:
- file: frontend/500.html

- error_code: over_quota
  file: frontend/over_quota.html